# main settings
title: Monero Docs
# email: docs@getmonero.org
description: >-
  Official Monero Documentation
baseurl: ""
url: "https://docs.getmonero.org"
twitter_username: monero
github_username: monero-project

# build settings
theme: just-the-docs

# just-the-docs settings
favicon_ico: "/assets/favicon-32x32.png"
search_enabled: true
show_sidebar: true
enable_copy_code_button: true
back_to_top: true
back_to_top_text: "Back to top"
footer_content: 'Copyright &copy; 2024, The Monero Project. Licensed under <a href="https://github.com/monero-project/monero-docs/blob/master/LICENSE.md">BSD 3-Clause "New" or "Revised" License</a>.'

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/monero-project/monero-docs"
gh_edit_branch: "master"
gh_edit_view_mode: "tree"
